version: "3"
services:
    mysql:
	   build:
		context: ./mysql
		environment:
			- MYSQL_DATABASE=mydatabase
			- MYSQL_USER=fernando
			- MYSQL_PASSWORD=password
			- MYSQL_ROOT_PASSWORD=password
	    networks:
            - mynetwork
    php:
        build:
            context: ./php
        ports:
            - "80:80"
        networks:
            - mynetwork
networks:
    mynetwork:


		

              
