# source mysql https://www.baeldung.com/ops/docker-mysql-container
version: "3"
services:
    mysql:
      build:
        context: ./mysql
        environment:
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
      ports:
            - "3306:3306"
      networks:
            - mynetwork
    php:
        build:
            context: ./php
        ports:
            - "80:80"
        networks:
            - mynetwork
networks:
    mynetwork:
