version: "3"

services:
    db:
       build:
            context: ./mysql
       ports:
            - "3306:3306"
       networks:
            - mynetwork
    php:
        build:
            context: ./php
        ports:
            - "80:80"
        networks:
            - mynetwork
networks:
    mynetwork:

              
