version: "3"

services:
    db:
       build:
            context: ./mysql
       networks:
            - symfony_app
    php:
        build:
            context: ./php
           
         networks:
            - symfony_app
    networks:
        symfony_app:
