version: "3"

services:
    db:
       build:
            context: ./mysql
       networks:
            - mynetwork
    php:
        build:
            context: ./php
        networks:
            - mynetwork
    networks:
        mynetwork:

              
